services:
  db:
    build: db
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./script:/docker-entrypoint-initdb.d
    env_file: ./.env
    ports:
      - "5432:5432"
volumes:
  db_volume:
